version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  # 👈 Frontend will be accessible via http://<your-ec2-public-ip>
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"  # API exposed on port 3001
