name = "car-finder"
main = "backend/index.js"
compatibility_date = "2025-07-01"

[build]
command = "npm install --prefix frontend && npm run build --prefix frontend"

[site]
bucket = "./frontend/dist"
